PirateBorgGenerator.Api/Models/CustomCharacterGeneratorModel.cs
namespace PirateBorgGenerator.Api.Models;

public class CustomCharacterGeneratorModel
{
    public bool EnableBrute {get; set;} = false;
    public bool EnableRapscallion {get; set;} = false;
    public bool EnableBuccaneer {get; set;} = false;
    public bool EnableSwashbuckler {get; set;} = false;
    public bool EnableZealot {get; set;} = false;
    public bool EnableSorcerer {get; set;} = false;

    public int NumPirates { get; set; } = 1;
}

PirateBorgGenerator.Api/Models/MultipleNewPirateRequest.cs
namespace PirateBorgGenerator.Api.Models;

public class MultipleNewPirateRequest
{
    public int NumPirates { get; set; } = 0;
    public bool Optional { get; set; } = false;

}

PirateBorgGenerator.Api/Models/NewCharacterRequest.cs
namespace PirateBorgGenerator.Api.Models;

public class NewCharacterRequest
{
    public string Name { get; set; } = "Nameless";
    public bool Optional { get; set; } = false;
}

PirateBorgGenerator.Api/Pages/Components/CharacterSheet/CharacterSheetViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PirateBorgGenerator.Api.Pages.Components.CharacterSheet;

public class CharacterSheetViewComponent: ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(Finalize.FinalCharacter? character = null)
    {
        character ??= Generation.generate("", true);
        return View(character);
    }
    
}

PirateBorgGenerator.Api/Pages/Components/GearListing/GearListingViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PirateBorgGenerator.Api.Pages.Components.GearListing;

public class GearListingViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync((string heading, string item) itemTuple) => View(itemTuple);

}

PirateBorgGenerator.Api/Pages/Components/StatBlock/StatBlockViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PirateBorgGenerator.Api.Pages.Components.StatBlock;

public class StatBlockViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(Character.StatBlock statBlock)
    {
        return View(statBlock);
    }
}

PirateBorgGenerator.Api/Pages/Components/WeaponBlock/WeaponBlockViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PirateBorgGenerator.Api.Pages.Components.WeaponBlock;

public class WeaponBlockViewComponent : ViewComponent
{
    
    
    public async Task<IViewComponentResult> InvokeAsync(string weapon, string description, string dieRoll) => 
        View((weapon, description, dieRoll));
    
}

PirateBorgGenerator.Api/Pages/CustomGenerator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class CustomGenerator : PageModel
{
    [BindProperty] public CustomCharacterGeneratorModel CustomCharacterGeneratorModel { get; set; } = new();
    
}

PirateBorgGenerator.Api/Pages/CustomPirates.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class CustomPirates : PageModel
{
    public Finalize.FinalCharacter[] Pirates { get; set; } = Array.Empty<Finalize.FinalCharacter>();


    public void OnPost(CustomCharacterGeneratorModel customCharacterGeneratorModel)
    {
        Pirates = new Finalize.FinalCharacter[Math.Min(customCharacterGeneratorModel.NumPirates, 20)];
        var classes = new List<string>();
        if (customCharacterGeneratorModel.EnableBrute) classes.Add("brute");
        if (customCharacterGeneratorModel.EnableRapscallion) classes.Add("rapscallion");
        if (customCharacterGeneratorModel.EnableBuccaneer) classes.Add("buccaneer");
        if (customCharacterGeneratorModel.EnableSwashbuckler) classes.Add("swashbuckler");
        if (customCharacterGeneratorModel.EnableZealot) classes.Add("zealot");
        if (customCharacterGeneratorModel.EnableSorcerer) classes.Add("sorcerer");
        if (classes.Count < 1)
        {
            RedirectToPage("CustomGenerator");
        }
        else
        {
            Parallel.For(0, Pirates.Length, i =>
            {
                Pirates[i] = Generation.generateFromClassList(classes.ToArray());
            });
        }
    }
}

PirateBorgGenerator.Api/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class IndexModel : PageModel
{
    [BindProperty] public MultipleNewPirateRequest PirateRequest { get; set; } 

    public void OnGet() {
    }
}

PirateBorgGenerator.Api/Pages/MakeNPirates.cshtml.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class MakeNPirates : PageModel
{
    [BindProperty] public MultipleNewPirateRequest Request { get; set; } 
}

PirateBorgGenerator.Api/Pages/MoarPirates.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class MoarPirates : PageModel
{
    public Finalize.FinalCharacter[] Pirates { get; set; } = Array.Empty<Finalize.FinalCharacter>();


    public void OnPost(MultipleNewPirateRequest pirateRequest)
    {
        Pirates = new Finalize.FinalCharacter[Math.Min(pirateRequest.NumPirates, 20)];

        Parallel.For(0, Pirates.Length, i =>
        {
            Pirates[i] = Generation.generate("Nameless", pirateRequest.Optional);
        });
    }
    
}

PirateBorgGenerator.Api/Pages/NewCharacter.cshtml.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PirateBorgGenerator.Api.Models;

namespace PirateBorgGenerator.Api.Pages;

public class NewCharacter : PageModel
{

    public Finalize.FinalCharacter _character;

    public void OnGet(NewCharacterRequest characterRequest)
    {
        _character = Generation.generate(characterRequest.Name, characterRequest.Optional);;
    }
   
}

PirateBorgGenerator.Api/Pages/Components/CharacterSheet/Default.cshtml
@using System.Text.RegularExpressions
@model PirateBorgGenerator.Finalize.FinalCharacter
<div class="character-sheet">
    <div class="character-basics">
        <div class="character-name-and-class">
            <h1>@Model.name</h1>
            <p>@Model.characterClass</p>
            <p>@Model.classAbility</p>
            <p class="ability-description">@Model.classAbilityDescription</p>
        </div>
        <hr>
        <div class="devils-luck">
            <p>HP: @Model.hitPoints</p>
            <p>Devil's Luck: @Model.devilsLuck (@Model.devilsLuckDie)</p>
        </div>
        <hr>
        <div class="optional-info">
            @if (!string.IsNullOrWhiteSpace(Model.tallTale))
            {
                @if (Regex.IsMatch(@Model.tallTale, @"[AEIOU].*"))
                {
                    <p>Is an @Model.tallTale</p>
                }
                else
                {
                    <p>Is a @Model.tallTale</p>
                }
            }
            @if (!string.IsNullOrWhiteSpace(Model.hauntedSoul))
            {
                @if (Regex.IsMatch(@Model.hauntedSoul, @"[AEIOU].*"))
                {
                    <p>Is an @Model.hauntedSoul</p>
                }
                else
                {
                    <p>Is a @Model.hauntedSoul</p>
                }
            }
        </div>
    </div>
    <vc:weapon-block weapon="@Model.startingWeapon" description="@Model.weaponDescription" die-roll="@Model.weaponDie"></vc:weapon-block>
    <vc:stat-block stat-block="Model.statBlock"></vc:stat-block>
    
    <div class="character-gear">
        <h2>Gear</h2>
        <ul>
            @if (!string.IsNullOrWhiteSpace(Model.container))
            {
                <li>@Model.container</li>
            }
            @if (!string.IsNullOrWhiteSpace(Model.cheapGear))
            {
                <li>@Model.cheapGear</li>
            }
            @if (!string.IsNullOrWhiteSpace(Model.fancyGear))
            {
                <li>@Model.fancyGear</li>
            }
            @if (!string.IsNullOrWhiteSpace(Model.startingHat))
            {
                <li>@Model.startingHat</li>
            }
            @if (!string.IsNullOrWhiteSpace(Model.startingClothes))
            {
                <li>@Model.startingClothes</li>
            }
        </ul>
    </div>
</div>

PirateBorgGenerator.Api/Pages/Components/GearListing/Default.cshtml
@model (string heading, string item)
<tr>
    <th scope="row" class="stat-block-stat-header">@Model.heading</th>
    <td class="gear-name">@Model.item</td>
</tr>

PirateBorgGenerator.Api/Pages/Components/StatBlock/Default.cshtml
@model PirateBorgGenerator.Character.StatBlock

<div class="stat-block">
    <table>
        <tr>
            <th scope="row" class="stat-block-stat-header">Strength</th>
            <td class="stat-block-stat-score">@Model.strength</td>
        </tr>
        <tr>
            <th scope="row" class="stat-block-stat-header">Toughness</th>
            <td class="stat-block-stat-score">@Model.toughness</td>
        </tr>
        <tr>
            <th scope="row" class="stat-block-stat-header">Presence</th>
            <td class="stat-block-stat-score">@Model.presence</td>
        </tr>
        <tr>
            <th scope="row" class="stat-block-stat-header">Agility</th>
            <td class="stat-block-stat-score">@Model.agility</td>
        </tr>
        <tr>
            <th scope="row" class="stat-block-stat-header">Spirit</th>
            <td class="stat-block-stat-score">@Model.spirit</td>
        </tr>
    </table>
</div>

PirateBorgGenerator.Api/Pages/Components/WeaponBlock/Default.cshtml
@model (string weapon, string description, string dieRoll)

@if (!string.IsNullOrWhiteSpace(Model.weapon))
{
<div class="weapon-block">
    <h2>Weapon</h2>
    <p>@Model.weapon (@Model.dieRoll)</p>
    @if (!string.IsNullOrWhiteSpace(Model.description))
    {
        <p class="ability-description">@Model.description</p>
    }
</div>
}

PirateBorgGenerator.Api/Pages/CustomGenerator.cshtml
@page
@model PirateBorgGenerator.Api.Pages.CustomGenerator

@{
    Layout = "Shared/_Layout";
}
<div class="custom-generator-form">
    <form method="post" asp-page="/CustomPirates">
        <label for="Brute-select">Do you want Brute?</label>
        <input type="checkbox" id="Brute-select" asp-for="CustomCharacterGeneratorModel.EnableBrute" />
        <label for="Rapscallion-select">Do you want Rapscallion?</label>
        <input type="checkbox" id="Rapscallion-select" asp-for="CustomCharacterGeneratorModel.EnableRapscallion" />
        <label for="Buccaneer-select">Do you want Buccaneer?</label>
        <input type="checkbox" id="Buccaneer-select" asp-for="CustomCharacterGeneratorModel.EnableBuccaneer" />
        <label for="Swashbuckler-select">Do you want Swashbuckler?</label>
        <input type="checkbox" id="Swashbuckler-select" asp-for="CustomCharacterGeneratorModel.EnableSwashbuckler" />
        <label for="Zealot-select">Do you want Zealot?</label>
        <input type="checkbox" id="Zealot-select" asp-for="CustomCharacterGeneratorModel.EnableZealot" />
        <label for="Sorcerer-select">Do you want Sorcerer?</label>
        <input type="checkbox" id="Sorcerer-select" asp-for="CustomCharacterGeneratorModel.EnableSorcerer" />
        <label for="number-pirates">How many scallywags ye be needin'?</label>
        <input type="number" id="number-pirates" asp-for="CustomCharacterGeneratorModel.NumPirates">
        
        <input type="submit" value="Set Sail!">
    </form>
</div>


<div>
    
</div>

PirateBorgGenerator.Api/Pages/CustomPirates.cshtml
@page
@model CustomPirates

@{
    Layout = "Shared/_Layout";
}

@for (var i = 0; i < Model.Pirates.Length; i+=2)
{
    <vc:character-sheet character="Model.Pirates[i]"></vc:character-sheet>
    <hr/>
    @if (i + 1 < Model.Pirates.Length)
    {
        <vc:character-sheet character="Model.Pirates[i+1]"></vc:character-sheet>
    }
    
}

PirateBorgGenerator.Api/Pages/Index.cshtml
@page
@model PirateBorgGenerator.Api.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Roll up a Scurvy Dog";
    Layout = "Shared/_Layout";
}
<vc:character-sheet></vc:character-sheet>
<div class="no-print kill-pirate">
    <a href="/">
        <img class="skull-button" src="img/skull-button-200x226.png" alt="To Davy Jones. . .">
    </a>
    <div>
        <p class="no-print">I don't like this one. . .</p>
    </div>

</div>
<div class="no-print">
    <a href="/CustomGenerator">Want to limit which scallywags ye create?</a>
    @* Bring this back when we add custom generation *@
    @* <form class="form" method="post"> *@
    @*     <div class="form-container"> *@
    @*         <label for="character-name">What Be Yer Name?</label> *@
    @*         <input type="text" class="text-input" id="character-name" asp-for="CharacterPirateRequest!.Name"/> *@
    @*     </div> *@
    @*     <div class="form-container"> *@
    @*         <label for="optional-classes">Do ye crave the chance at bein' undead or mythical?</label> *@
    @*         <input type="checkbox" class="checkbox-input" id="optional-classes" asp-for="CharacterPirateRequest!.Optional"/> *@
    @*     </div> *@
    @*     <input type="submit" value="Set Sail!" class="submit"/> *@
    @* </form> *@
    <h1>Need more?</h1>
    <form method="post" asp-page="/MoarPirates">
    @* <form method="post"> *@
        <div>
            <label for="number-pirates">How many scallywags ye be needin'?</label>
            <input type="number" id="number-pirates" asp-for="PirateRequest.NumPirates">
        </div>
        <div>
            <label for="optional-pirates">Do ye want them to be extra special?</label>
            <input type="checkbox" id="optional-pirates" asp-for="PirateRequest.Optional">
        </div>
        <input type="submit" value="Moar Pirates!">
    </form>
</div>

PirateBorgGenerator.Api/Pages/MakeNPirates.cshtml
@page
@model PirateBorgGenerator.Api.Pages.MakeNPirates

@{
    Layout = "Shared/_Layout";
    ViewData["title"] = "Meat to the Slaughter";
}
<div class="no-print">
    <form method="post" asp-page="/MoarPirates">
        <div>
            <label for="number-pirates">How many scallywags ye be needin'?</label>
            <input type="number" id="number-pirates" asp-for="Request.NumPirates">
        </div>
        <div>
            <label for="optional-pirates">Do ye want them to be extra special?</label>
            <input type="checkbox" id="optional-pirates" asp-for="Request.Optional">
        </div>
        <input type="submit" value="Moar Pirates!">
    </form>
</div>

PirateBorgGenerator.Api/Pages/MoarPirates.cshtml
@page
@model PirateBorgGenerator.Api.Pages.MoarPirates

@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = "Moar Pirates";
}

@for (var i = 0; i < Model.Pirates.Length; i+=2)
{
    <vc:character-sheet character="Model.Pirates[i]"></vc:character-sheet>
    <hr/>
    @if (i + 1 < Model.Pirates.Length)
    {
        <vc:character-sheet character="Model.Pirates[i+1]"></vc:character-sheet>
    }
    
}

PirateBorgGenerator.Api/Pages/NewCharacter.cshtml
@page
@model PirateBorgGenerator.Api.Pages.NewCharacter

@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = Model._character.name;

}

<vc:character-sheet character="Model._character"></vc:character-sheet>

PirateBorgGenerator.Api/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="/css/site.css"/>
</head>
<body>
    <div id="page-content">
        @RenderBody()
    </div>

</body>
</html>